config/routes.rb
Kursusbase2012::Application.routes.draw do

  scope "(:locale)", :locale => /en|da/ do
    
    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'application#login', as: 'sessions'
    put 'login', to: 'application#login', as: 'sessions'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    
    resources :courses, only: [:index, :show]
		resources :studyplan_items, :path => '/studyplan', :only => [:create, :update, :destroy] do
			get 'show', :path => '(/:semester)', :as => 'studyplan', :on => :collection
		end
		
		post "/search", to: "courses#index", as: "search"
		
		get '/searchtips', to: 'pages#searchtips', as: 'searchtips'
		
		root :to => 'students#show'
  end  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :set_locale
  
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end
  
  def set_locale
    I18n.locale = params[:locale] || cookies[:locale] || I18n.default_locale
    cookies[:locale] = I18n.locale
  end

	def call_rake(task, options = {})
	  options[:rails_env] ||= Rails.env
	  args = options.map { |n, v| "#{n.to_s.upcase}='#{v}'" }
	  system "/usr/bin/rake #{task} #{args.join(' ')} --trace 2>&1 >> #{Rails.root}/log/rake.log &"
	end
	
	def login
    @student = Student.find_or_initialize_by_student_number(params[:student][:student_number])

		# Dummy field of study
		field_of_study = FieldOfStudy.find_by_title('Softwareteknologi')
    @student.field_of_study = field_of_study

    @student.password = params[:student][:password]
    if @student.authenticate(params[:student][:password]) && (
      if @student.new_record? || @student.user_id.nil?
        @student.update_info
      else
        @student.save
      end ) 
      
      session[:student_id] = @student.id
      @student.update_courses
      
      respond_to do |format|
        format.html { redirect_to root_url, notice: "Logged in!" }
        format.js   { redirect_to root_url, notice: "Logged in!" }
      end
    else
      flash[:alert] = @student.errors[:base]
      respond_to do |format|
        format.html { redirect_to flash[:return_url] || root_url }
        format.js   { render :nothing => true, :json => { :error => @student.errors[:base].first }, :status => :unprocessable_entity }
      end
    end
  end
  
  private

  def current_student
    puts "HEJ"
    @current_student ||= Student.find(session[:student_id]) if session[:student_id] && Student.exists?(session[:student_id])
  end
  helper_method :current_student

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_student.nil?
  end
  
  def alt_language
    if I18n.locale == :da
      :en
    elsif I18n.locale == :en
      :da
    end
  end
  helper_method :alt_language
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
		content_for :title, page_title.to_s
	end
end

app/views/application/_header.html.erb
<% you = current_student %>
<div id="head"><div><div>
	<h1><a href="<%= root_path %>"><span><%= t('sitename') %></span></a></h1>
	<%= render_navigation %>
	<%= form_tag courses_path, :method => :get do %>
		<%= text_field_tag :search, params[:search], :tabindex => 1, :placeholder => t('splaceholder') %>
	<% end %>
<div id="you"><% if you %>
	<%= t('you.are') %> <strong><%= you.fullname %></strong>. <a href="/logout"><%= t('you.logout') %></a>
<% else %>
	<a href="/login"><%= t('you.login') %></a>
<% end %></div>
</div></div></div>

app/views/application/_lhbar.html.erb
<% if ["127.0.0.1", "localhost", "0.0.0.0"].include? request.host %>
<div id="localhost">Local host <a href="http://kursusbase2012.herokuapp.com<%= request.path %>"><%= t('internal.onheroku') %></a></div><%
	end %>

app/views/application/login.js.erb
alert("hej");